version: '3.3'

services:
  funpay-wizard:
    image: neluckoff/funpay-wizard
    build: ./
    container_name: funpay-wizard
    restart: unless-stopped
    tty: true
    environment:
      - TZ=Europe/Moscow
      - TELEGRAM_PROXY_URL=${TELEGRAM_PROXY_URL:-}
    volumes:
      - ./configs:/app/configs
      - ./storage:/app/storage
      - ./logs:/app/logs
